version: '3.8'

services:
  app:
    container_name: asyncapi-website  # For easier container identification
    build:
      context: .
      dockerfile: Dockerfile # Path to Dockerfile
    ports:
      - "3000:3000"          # Map host port 3000 to container port 3000
    volumes:
      - .:/async             # Mount the current directory to /async in the container - for hot reloading
      - /async/node_modules  # Exclude node_modules from being overridden
    environment:
      NODE_ENV: development  # Set environment variable
    command: ["npm", "run", "dev"]
    restart: unless-stopped  # Automatic container recovery
    healthcheck:            # Container health monitoring
      test: ["CMD", "wget", "--spider", "-q", "localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
